### ISSUE TITLE
npm ERR! código 1

### ISSUE THREAD

**Issue by sathler1** [cleitonleonel/Impressora_GP_iFood#1]
npm ERR! code 1
npm ERR! path /home/sathler/Impressora_GP_iFood/node_modules/@thiagoelg/node-printer
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.19.1 runtime=node arch=x64 libc= platform=linux)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@18.19.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.12.3 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/sathler/Impressora_GP_iFood/node_modules/@thiagoelg/node-printer/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/include/nodejs/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/arielle-sathler/Impressora_GP_iFood/node_modules/@thiagoelg/node-printer',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: 1: cups-config: not found
npm ERR! gyp: Call to 'cups-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:329:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm ERR! gyp ERR! System Linux 6.8.0-38-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/share/nodejs/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/sathler/Impressora_GP_iFood/node_modules/@thiagoelg/node-printer
npm ERR! gyp ERR! node -v v18.19.1
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sathler/.npm/_logs/2024-07-30T03_57_52_580Z-debug-0.log

**Comment by cleitonleonel** [comment]
Se você usa Linux então precisa ter o cups instalado, bem como suas dependências.
Tente instalar por esse via terminal por esse comando:
```sudo apt install cups build-essential libcups2-dev libcupsimage2-dev```

**Comment by sathler1** [comment]
o erro persiste, acredito que seja pela  versão do node 18.19.1 .
parece que esta dependência @thiagoelg/node-printer só funciona ate a versão 13

**Comment by cleitonleonel** [comment]
> o erro persiste, acredito que seja pela versão do node 18.19.1 . parece que esta dependência @thiagoelg/node-printer só funciona ate a versão 13

Vou tentar reproduzir isso, mas já usei em versões mais recentes do node.
Deixe esta issue aberta, pois irei tentar reproduzir isso.

Fique a vontade para testar a versão em python: https://github.com/cleitonleonel/Impressora_GP_PyFood

**Comment by cleitonleonel** [comment]
> o erro persiste, acredito que seja pela versão do node 18.19.1 . parece que esta dependência @thiagoelg/node-printer só funciona ate a versão 13

Posso confirmar que é de fato a versão do node, consegui reproduzir aqui o seu relato e o que funcionou foi usar nvm com a versão 12 do node.

**Comment by cleitonleonel** [comment]
![image](https://github.com/user-attachments/assets/99769ad8-442a-4564-b145-c329aeb7585c)

**Comment by sathler1** [comment]
super resolvido, muito obrigado!!
